services:
  altair-os:
    image: adisha-os
    container_name: adisha-os
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/i2c-1:/dev/i2c-1
      - /dev/gpiomem:/dev/gpiomem
    volumes:
      - ./src:/adisha-os/src
      - ./web:/adisha-os/web
      - /sys:/sys
    ports:
      - "3000:3000"